server:
  port: 8088

spring:
  application:
    name: marketcali-monolith
  datasource:
    url: jdbc:mysql://mysql-db:3306/marketcali_db
    username: miguel
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: 4GJW5A9H8HFW5D3AS7CZF1T9E3D6B5A18C3B8H4D1F0E # same as before if any, else this default
  expiration: 86400000

logging:
  level:
    org.springframework.security: DEBUG
